#############################################################################
# Makefile for building: Webcam
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  Webcam.pro
# Template: app
# Command: /home/canberk/Qt/5.5/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile Webcam.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/opencv -I/home/canberk/Qt/5.5/gcc_64/include -I/home/canberk/Qt/5.5/gcc_64/include/QtWidgets -I/home/canberk/Qt/5.5/gcc_64/include/QtGui -I/home/canberk/Qt/5.5/gcc_64/include/QtCore -I. -I. -I/home/canberk/Qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/canberk/Qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Webcam1.0.0
DISTDIR = /home/canberk/Documents/QtCreator/OpenCV/FollowBall/Webcam/.tmp/Webcam1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/canberk/Qt/5.5/gcc_64 -Wl,-rpath,/home/canberk/Qt/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -lopencv_core -lopencv_imgcodecs -lopencv_highgui -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_videoio -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_hal -L/home/canberk/Qt/5.5/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /home/canberk/Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/resources.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/moc.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/uic.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		Webcam.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = Webcam
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Webcam


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Webcam.pro /home/canberk/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf /home/canberk/Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/resources.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/moc.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/uic.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		/home/canberk/Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		Webcam.pro \
		/home/canberk/Qt/5.5/gcc_64/lib/libQt5Widgets.prl \
		/home/canberk/Qt/5.5/gcc_64/lib/libQt5Gui.prl \
		/home/canberk/Qt/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Webcam.pro
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/common/unix.conf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/common/linux.conf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/qconfig.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/default_post.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/qt.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/resources.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/moc.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/uic.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/yacc.prf:
/home/canberk/Qt/5.5/gcc_64/mkspecs/features/lex.prf:
Webcam.pro:
/home/canberk/Qt/5.5/gcc_64/lib/libQt5Widgets.prl:
/home/canberk/Qt/5.5/gcc_64/lib/libQt5Gui.prl:
/home/canberk/Qt/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Webcam.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /home/canberk/Qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qicon.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/QTimer \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtimer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbasictimer.h \
		mainwindow.h
	/home/canberk/Qt/5.5/gcc_64/bin/moc $(DEFINES) -I/home/canberk/Qt/5.5/gcc_64/mkspecs/linux-g++ -I/home/canberk/Documents/QtCreator/OpenCV/FollowBall/Webcam -I/usr/local/include/opencv -I/home/canberk/Qt/5.5/gcc_64/include -I/home/canberk/Qt/5.5/gcc_64/include/QtWidgets -I/home/canberk/Qt/5.5/gcc_64/include/QtGui -I/home/canberk/Qt/5.5/gcc_64/include/QtCore mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/canberk/Qt/5.5/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qicon.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/QTimer \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtimer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbasictimer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/QApplication \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtGui/qicon.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/QTimer \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtimer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbasictimer.h \
		ui_mainwindow.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/QtCore \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/QtCoreDepends \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qabstractanimation.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qanimationgroup.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qparallelanimationgroup.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpauseanimation.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpropertyanimation.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qvariantanimation.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qeasingcurve.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtextcodec.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qendian.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlibraryinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qdatetime.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbuffer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qdir.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfileinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qdiriterator.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfileselector.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/QObject \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/QStringList \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfilesystemwatcher.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlockfile.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qloggingcategory.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qprocess.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qresource.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsavefile.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsettings.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstandardpaths.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstorageinfo.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtemporarydir.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/QScopedPointer \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtemporaryfile.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qabstractproxymodel.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qidentityproxymodel.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qitemselectionmodel.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstringlistmodel.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qjsonarray.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qjsonvalue.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qjsondocument.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qjsonobject.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmath.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmetaobject.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmimedata.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpointer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsharedmemory.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsignalmapper.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsocketnotifier.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsystemsemaphore.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtranslator.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qwineventnotifier.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmimedatabase.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmimetype.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfactoryinterface.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlibrary.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qplugin.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qpluginloader.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/quuid.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qabstractstate.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qabstracttransition.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qeventtransition.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfinalstate.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qhistorystate.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsignaltransition.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstate.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstatemachine.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qexception.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfuture.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfutureinterface.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qrunnable.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qresultstore.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfuturesynchronizer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qfuturewatcher.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qreadwritelock.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qsemaphore.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qthread.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qthreadpool.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qthreadstorage.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qwaitcondition.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qarraydataops.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qarraydatapointer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbitarray.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qbytearraymatcher.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcache.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcollator.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcommandlineoption.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcommandlineparser.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qcryptographichash.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qelapsedtimer.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qlinkedlist.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qqueue.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qscopedvaluerollback.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qstack.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtextboundaryfinder.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtimeline.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtimezone.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qxmlstream.h \
		/home/canberk/Qt/5.5/gcc_64/include/QtCore/qtcoreversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

